// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAA_MVC_W.AccesoDatos.Data;

#nullable disable

namespace PAA_MVC_W.AccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240823223139_AgregarmodelosUsuarioRolporequivicacion")]
    partial class AgregarmodelosUsuarioRolporequivicacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAA_MVC_W.Modelos.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ActividadControl")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaIndicador")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DireccionGeneralId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Especificaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha4")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedioVerificacionProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivoActividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ObjetivoClave")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Supuestos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("UnidadAuditoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionGeneralId");

                    b.HasIndex("UnidadAuditoraId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bis")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DireccionGeneralId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.Property<int>("UnidadAuditoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionGeneralId");

                    b.HasIndex("UnidadAuditoraId");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.DireccionGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cc")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre_DG")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadAuditoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadAuditoraId");

                    b.ToTable("DireccionGenerals");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Fraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("Bis")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Frac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Fraccions");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.UnidadAuditora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cc")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre_UA")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("UnidadAuditoras");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("DireccionGeneralId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UnidadAuditoraId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionGeneralId");

                    b.HasIndex("UnidadAuditoraId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuarioRols");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Actividad", b =>
                {
                    b.HasOne("PAA_MVC_W.Modelos.DireccionGeneral", "DireccionGeneral")
                        .WithMany()
                        .HasForeignKey("DireccionGeneralId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAA_MVC_W.Modelos.UnidadAuditora", "UnidadAuditora")
                        .WithMany()
                        .HasForeignKey("UnidadAuditoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DireccionGeneral");

                    b.Navigation("UnidadAuditora");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Articulo", b =>
                {
                    b.HasOne("PAA_MVC_W.Modelos.DireccionGeneral", "DireccionGeneral")
                        .WithMany()
                        .HasForeignKey("DireccionGeneralId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAA_MVC_W.Modelos.UnidadAuditora", "UnidadAuditora")
                        .WithMany()
                        .HasForeignKey("UnidadAuditoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DireccionGeneral");

                    b.Navigation("UnidadAuditora");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.DireccionGeneral", b =>
                {
                    b.HasOne("PAA_MVC_W.Modelos.UnidadAuditora", "UnidadAuditora")
                        .WithMany()
                        .HasForeignKey("UnidadAuditoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UnidadAuditora");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Fraccion", b =>
                {
                    b.HasOne("PAA_MVC_W.Modelos.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Usuario", b =>
                {
                    b.HasOne("PAA_MVC_W.Modelos.DireccionGeneral", "DireccionGeneral")
                        .WithMany()
                        .HasForeignKey("DireccionGeneralId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAA_MVC_W.Modelos.UnidadAuditora", "UnidadAuditora")
                        .WithMany()
                        .HasForeignKey("UnidadAuditoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DireccionGeneral");

                    b.Navigation("UnidadAuditora");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.UsuarioRol", b =>
                {
                    b.HasOne("PAA_MVC_W.Modelos.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAA_MVC_W.Modelos.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("PAA_MVC_W.Modelos.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
